apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: producer-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      serviceAccountName: msk-sa
      containers:
      - name: producer
        image: kafka
        env:
        - name: BOOTSTRAP
          valueFrom:
            configMapKeyRef:
              name: msk-bootstrap
              key: bootstrapServers
        command:
        - sh
        - -c
        - |
          while true; do
            echo "Hello Kafka from Kubernetes $(date)" | /opt/kafka/bin/kafka-console-producer.sh \
              --bootstrap-server ${BOOTSTRAP} \
              --topic kafka-demo-topic \
              --command-config /config/client.properties
            sleep 2
          done  
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: msk-client-config
