apiVersion: v1
kind: Namespace
metadata:
  name: producer-consumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msk-client-config
  namespace: producer-consumer
data:
  client.properties: |
    security.protocol=SASL_SSL
    sasl.mechanism=AWS_MSK_IAM
    sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msk-sa
  namespace: producer-consumer
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::027330342406:role/aws-irsa-role
